version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: inkspot_postgres_dev
    environment:
      POSTGRES_DB: inkspot
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Z4qtMeWAXz7Bi5Sp
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    networks:
      - inkspot_network_dev
    restart: unless-stopped

  # Redis for caching and sessions
  redis:
    image: redis:7-alpine
    container_name: inkspot_redis_dev
    command: redis-server --requirepass v4icOhDasY3eCVrQ
    ports:
      - "6379:6379"
    volumes:
      - redis_data_dev:/data
    networks:
      - inkspot_network_dev
    restart: unless-stopped

  # MailHog for email testing
  mailhog:
    image: mailhog/mailhog:latest
    container_name: inkspot_mailhog_dev
    ports:
      - "1025:1025"  # SMTP port
      - "8025:8025"  # Web UI port
    networks:
      - inkspot_network_dev
    restart: unless-stopped

  # Grafana for monitoring
  grafana:
    image: grafana/grafana:latest
    container_name: inkspot_grafana_dev
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - "3001:3000"
    volumes:
      - grafana_data_dev:/var/lib/grafana
    networks:
      - inkspot_network_dev
    restart: unless-stopped

  # Prometheus for metrics
  prometheus:
    image: prom/prometheus:latest
    container_name: inkspot_prometheus_dev
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data_dev:/prometheus
    networks:
      - inkspot_network_dev
    restart: unless-stopped

volumes:
  postgres_data_dev:
  redis_data_dev:
  grafana_data_dev:
  prometheus_data_dev:

networks:
  inkspot_network_dev:
    driver: bridge
