global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets: []

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Node Exporter for system metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  # Postgres Exporter for database metrics
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']

  # INKSPOT Application metrics
  - job_name: 'inkspot-app'
    metrics_path: '/api/metrics'
    static_configs:
      - targets: ['host.docker.internal:3000']  # Adjust based on your setup
    scrape_interval: 30s

  # Redis metrics (if Redis exporter is added)
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']