global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # INKSPOT Application
  - job_name: 'inkspot-app'
    static_configs:
      - targets: ['app:3000']
    metrics_path: '/api/metrics'
    scrape_interval: 10s

  # Node Exporter
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  # PostgreSQL Exporter
  - job_name: 'postgres-exporter'
    static_configs:
      - targets: ['postgres-exporter:9187']

  # Redis Exporter (if you add one)
  # - job_name: 'redis-exporter'
  #   static_configs:
  #     - targets: ['redis-exporter:9121']

  # Custom INKSPOT metrics
  - job_name: 'inkspot-custom'
    static_configs:
      - targets: ['app:3000']
    metrics_path: '/api/grafana'
    scrape_interval: 5s
    honor_labels: true
