apiVersion: 1

datasources:
  - name: INKSPOT JSON API
    type: simplejson
    access: proxy
    url: http://app:3000/api/grafana
    jsonData:
      httpMethod: POST
      timeInterval: "5s"
    editable: true
    isDefault: true

  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    editable: true

  - name: PostgreSQL
    type: postgres
    access: proxy
    url: postgres:5432
    database: inkspot
    user: postgres
    secureJsonData:
      password: postgres
    jsonData:
      sslmode: disable
      maxOpenConns: 100
      maxIdleConns: 100
      connMaxLifetime: 14400
    editable: true
