apiVersion: 1

datasources:
  # Prometheus — métriques système et infra
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      timeInterval: "15s"

  # INKSPOT JSON API — métriques métier custom
  - name: INKSPOT JSON API
    type: simpod-json-datasource
    access: proxy
    url: http://inkspot-app:3000/api/grafana
    editable: true
    jsonData:
      keepCookies: []

  # Loki — logs applicatifs
  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    editable: true

  # Tempo — traces distribuées
  - name: Tempo
    type: tempo
    access: proxy
    url: http://tempo:3200
    editable: true
    jsonData:
      tracesToLogs:
        datasourceUid: loki
        tags: ["job", "instance"]
      serviceMap:
        datasourceUid: prometheus
