apiVersion: 1

datasources:
  # Prometheus datasource
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true

  # PostgreSQL datasource for direct database queries
  - name: PostgreSQL
    type: postgres
    access: proxy
    url: postgres:5432  # Adjust based on your PostgreSQL setup
    database: ${POSTGRES_DB}
    user: ${POSTGRES_USER}
    secureJsonData:
      password: ${POSTGRES_PASSWORD}
    jsonData:
      sslmode: disable
      maxOpenConns: 100
      maxIdleConns: 100
      connMaxLifetime: 14400
    editable: true

  # JSON API datasource for custom app metrics
  - name: INKSPOT-API
    type: grafana-simple-json-datasource
    access: proxy
    url: http://host.docker.internal:3000/api/grafana
    editable: true
    jsonData:
      httpMethod: GET